"""add_auth_comms_tables

Revision ID: 29d0831ebf0e
Revises: a5235fe062dd
Create Date: 2026-06-24 11:24:31.718047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29d0831ebf0e'
down_revision: Union[str, Sequence[str], None] = 'a5235fe062dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_events',
    sa.Column('auth_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ship_id', sa.String(), nullable=False),
    sa.Column('ship_name', sa.String(), nullable=False),
    sa.Column('challenge', sa.Text(), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('session_key_fingerprint', sa.String(), nullable=False),
    sa.Column('success', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('auth_id')
    )
    op.create_index(op.f('ix_auth_events_ship_id'), 'auth_events', ['ship_id'], unique=False)
    op.create_table('control_center_identity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('private_key_pem', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ship_id', sa.String(), nullable=False),
    sa.Column('ship_name', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('message_type', sa.String(), nullable=False),
    sa.Column('ciphertext_hex', sa.Text(), nullable=False),
    sa.Column('iv_hex', sa.String(), nullable=False),
    sa.Column('plaintext_preview', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_messages_ship_id'), 'messages', ['ship_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_ship_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('control_center_identity')
    op.drop_index(op.f('ix_auth_events_ship_id'), table_name='auth_events')
    op.drop_table('auth_events')
    # ### end Alembic commands ###
