"""initial schema

Revision ID: a5235fe062dd
Revises: 
Create Date: 2026-06-23 18:18:22.842625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5235fe062dd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('alert_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ship_id', sa.String(), nullable=True),
    sa.Column('ship_name', sa.String(), nullable=True),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('block_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_index(op.f('ix_alerts_ship_id'), 'alerts', ['ship_id'], unique=False)
    op.create_table('blocks',
    sa.Column('block_index', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ship_id', sa.String(), nullable=True),
    sa.Column('ship_name', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('signer_pub_key', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('prev_hash', sa.String(), nullable=False),
    sa.Column('block_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('block_index')
    )
    op.create_index(op.f('ix_blocks_ship_id'), 'blocks', ['ship_id'], unique=False)
    op.create_table('restricted_zones',
    sa.Column('zone_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('zone_type', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('radius_km', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('zone_id')
    )
    op.create_table('ships',
    sa.Column('ship_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('imo_number', sa.String(), nullable=True),
    sa.Column('ship_type', sa.String(), nullable=True),
    sa.Column('origin_port', sa.String(), nullable=True),
    sa.Column('origin_lat', sa.Float(), nullable=True),
    sa.Column('origin_lon', sa.Float(), nullable=True),
    sa.Column('dest_port', sa.String(), nullable=True),
    sa.Column('dest_lat', sa.Float(), nullable=True),
    sa.Column('dest_lon', sa.Float(), nullable=True),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('private_key_pem', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('certificate_hash', sa.Text(), nullable=False),
    sa.Column('current_lat', sa.Float(), nullable=True),
    sa.Column('current_lon', sa.Float(), nullable=True),
    sa.Column('current_speed', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('ship_id')
    )
    op.create_table('used_nonces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ship_id', sa.String(), nullable=False),
    sa.Column('nonce', sa.String(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ship_id', 'nonce', name='uq_used_nonces_ship_nonce')
    )
    op.create_index(op.f('ix_used_nonces_ship_id'), 'used_nonces', ['ship_id'], unique=False)
    op.create_table('weather_readings',
    sa.Column('reading_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('wind_speed_kmh', sa.Float(), nullable=False),
    sa.Column('pressure_hpa', sa.Float(), nullable=False),
    sa.Column('wave_height_m', sa.Float(), nullable=True),
    sa.Column('rainfall_mm', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('reading_id')
    )
    op.create_table('positions',
    sa.Column('position_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ship_id', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signature_valid', sa.Integer(), nullable=False),
    sa.Column('block_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ship_id'], ['ships.ship_id'], ),
    sa.PrimaryKeyConstraint('position_id')
    )
    op.create_index(op.f('ix_positions_ship_id'), 'positions', ['ship_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_positions_ship_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_table('weather_readings')
    op.drop_index(op.f('ix_used_nonces_ship_id'), table_name='used_nonces')
    op.drop_table('used_nonces')
    op.drop_table('ships')
    op.drop_table('restricted_zones')
    op.drop_index(op.f('ix_blocks_ship_id'), table_name='blocks')
    op.drop_table('blocks')
    op.drop_index(op.f('ix_alerts_ship_id'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
