"""Add last_moved_at to ships

Revision ID: c9b497ab1b2d
Revises: 7e6df068f15f
Create Date: 2026-07-12 17:46:37.949867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9b497ab1b2d'
down_revision: Union[str, Sequence[str], None] = '7e6df068f15f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ships', sa.Column('last_moved_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ships', 'last_moved_at')
    # ### end Alembic commands ###
