"""add voyages table

Revision ID: e0907711dcdf
Revises: c4e7f92a1b3d
Create Date: 2026-06-30 04:46:25.253090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0907711dcdf'
down_revision: Union[str, Sequence[str], None] = 'c4e7f92a1b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voyages',
    sa.Column('voyage_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ship_id', sa.String(), nullable=False),
    sa.Column('origin_port', sa.String(), nullable=False),
    sa.Column('origin_lat', sa.Float(), nullable=False),
    sa.Column('origin_lon', sa.Float(), nullable=False),
    sa.Column('dest_port', sa.String(), nullable=False),
    sa.Column('dest_lat', sa.Float(), nullable=False),
    sa.Column('dest_lon', sa.Float(), nullable=False),
    sa.Column('current_lat', sa.Float(), nullable=True),
    sa.Column('current_lon', sa.Float(), nullable=True),
    sa.Column('current_speed_kmh', sa.Float(), nullable=False),
    sa.Column('geofence_radius_km', sa.Float(), nullable=False),
    sa.Column('distance_total_km', sa.Float(), nullable=False),
    sa.Column('distance_travelled_km', sa.Float(), nullable=False),
    sa.Column('distance_remaining_km', sa.Float(), nullable=False),
    sa.Column('eta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('expected_departure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ship_id'], ['ships.ship_id'], ),
    sa.PrimaryKeyConstraint('voyage_id')
    )
    op.create_index(op.f('ix_voyages_ship_id'), 'voyages', ['ship_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voyages_ship_id'), table_name='voyages')
    op.drop_table('voyages')
    # ### end Alembic commands ###
